version: '3'
services:
  scrambled-words:
    build:
      context: '.'
      args:
        REQUIREMENTS_FILE: './requirements.txt'
        STARTING_DIR: '/src'
    volumes:
      - ./src:/src
    image: scrambled-words
